version: '3'
services:
  db:
    image: postgres:10.7-alpine
    ports:
      - "5432:5432"
  app:
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app
    environment:
      BUNDLE_PATH: .bundle